README.md
=> chore: 修改文档贡献内容

package.json
=> chore: npm 发布移除 src 目录

src/components/CustomControl/types.ts, src/components/LarkMap/demo/default.tsx, src/components/LarkMap/demo/mapbox-instance.tsx, src/components/LarkMap/index.md, src/components/LarkMap/types.ts, src/components/Layers/BubbleLayer/index.md, src/components/Layers/BubbleLayer/index.tsx, src/components/Layers/BubbleLayer/types.ts, src/components/Layers/ChoroplethLayer/index.tsx, src/components/Layers/ChoroplethLayer/types.ts, src/components/Layers/hooks/use-create-layer.ts, src/components/Template/types.ts, src/types/common.ts
- 简化图层组件代码
- 图层组件支持创建回调函数
- 图层组件支持 ref
- 新增“如何获取图层实例？”文档
1. 通过 onCreated 回调
```tsx | pure
import { BubbleLayer, LarkMap } from '@antv/larkmap';
import React from 'react';
const source = {
data: [
{ lng: 120.210792, lat: 30.246026, c: 'red', t: 20, n: '杭州' },
{ lng: 121.473667, lat: 31.230525, c: 'blue', t: 24, n: '上海' },
],
parser: { type: 'json', x: 'lng', y: 'lat' },
};
export default () => {
const onLayerCreated = (layer) => {
console.log(layer);
};
return (
<LarkMap mapType="GaodeV1" style={{ height: '300px' }}>
<BubbleLayer
ref={bubbleLayerRef}
source={source}
autoFit={true}
radius={40}
fillColor="#0f9960"
opacity={0.4}
strokeColor="blue"
lineWidth={2}
onCreated={onLayerCreated}
/>
</LarkMap>
);
};
```
2. 挂载到 ref 上
```tsx | pure
import { BubbleLayer, LarkMap } from '@antv/larkmap'; …
```
=> refactor: 简化图层组件创建

.umirc.ts, package.json, src/components/LarkMap/hooks/use-layer/demos/default.tsx, src/components/LarkMap/index.tsx, src/components/Layers/BubbleLayer/demos/default.tsx, src/components/Layers/BubbleLayer/index.tsx, src/components/Layers/ChoroplethLayer/demos/default.tsx, src/components/Layers/ChoroplethLayer/index.tsx, src/components/Layers/hooks/use-create-layer.ts, src/version.ts
=> fix: 修复地图状态更新

package.json, src/components/Scale/demos/default.tsx, src/components/Scale/index.md, src/components/Scale/index.tsx, src/components/Scale/types.ts, src/components/Template/demos/default.tsx, src/components/Zoom/demos/default.tsx, src/components/Zoom/index.md, src/components/Zoom/index.tsx, src/components/Zoom/types.ts, src/index.ts, src/version.ts
=> feat: 新增控件 zoom、scale

src/components/CustomControl/index.tsx, src/components/LarkMap/index.tsx, src/components/Layers/BubbleLayer/index.tsx, src/components/Layers/ChoroplethLayer/index.tsx, src/components/Layers/HeatmapLayer/index.tsx, src/components/Layers/LineLayer/index.tsx, src/components/Layers/PointLayer/index.tsx, src/components/Layers/PolygonLayer/index.tsx, src/components/Layers/TextLayer/index.tsx, src/components/Scale/index.tsx, src/components/Template/index.tsx, src/components/Zoom/index.tsx, src/index.ts
=> chore: 规范包引入顺序

src/components/CustomControl/types.ts, src/components/Marker/demos/default.tsx, src/components/Marker/index.md, src/components/Marker/index.tsx, src/components/Marker/types.ts, src/components/Scale/index.tsx, src/components/Scale/types.ts, src/components/Zoom/index.tsx, src/components/Zoom/types.ts, src/index.ts
=> feat: 新增 marker 组件

package.json, src/version.ts
=> chore: v0.0.1-alpha.5

src/components/CustomControl/index.md, src/components/LarkMap/index.tsx, src/components/Marker/index.md, src/components/Marker/index.tsx, src/components/Marker/types.ts, src/components/Popup/demos/default.tsx, src/components/Popup/index.md, src/components/Popup/types.ts, src/components/Scale/index.md, src/components/Template/index.md, src/components/Zoom/index.md
=> fix: 修复资源注册问题

src/components/LarkMap/hooks/use-layer-manager/index.ts, src/components/LarkMap/hooks/use-scene/index.ts, src/components/Layers/BubbleLayer/demos/default.tsx, src/components/Layers/ChoroplethLayer/demos/default.tsx, src/components/Layers/hooks/use-create-layer.ts
=> chore: 给错误使用加提示信息

package.json, src/components/Draw/use-draw-group/demos/default.less, src/components/Draw/use-draw-group/demos/default.tsx, src/components/Draw/use-draw-group/index.md, src/components/Draw/use-draw-group/index.ts, src/components/Draw/use-draw-group/types.ts, src/components/Draw/use-draw/demos/default.tsx, src/components/Draw/use-draw/demos/options.tsx, src/components/Draw/use-draw/index.md, src/components/Draw/use-draw/index.ts, src/index.ts
=> feat: 新增绘制 Hook：useDrawGroup

src/components/LarkMap/index.tsx, src/components/LayerAttribute/BubbleLayerStyle/demos/default.tsx, src/components/LayerAttribute/BubbleLayerStyle/index.tsx, src/components/LayerAttribute/ChoroplethLayerStyle/demos/default.tsx, src/components/LayerAttribute/ChoroplethLayerStyle/index.tsx, src/components/Layers/BaseLayers/HeatmapLayer/demos/default.tsx, src/components/Layers/BaseLayers/HeatmapLayer/index.tsx, src/components/Layers/BaseLayers/LineLayer/demos/default.tsx, src/components/Layers/BaseLayers/LineLayer/index.tsx, src/components/Layers/BaseLayers/PointLayer/index.tsx, src/components/Layers/BaseLayers/PolygonLayer/index.tsx, src/components/Layers/BaseLayers/TextLayer/demos/default.tsx, src/components/Layers/BaseLayers/TextLayer/index.tsx, src/components/Layers/CompositeLayers/BubbleLayer/index.tsx, src/components/Layers/CompositeLayers/ChoroplethLayer/index.tsx, src/components/Marker/index.tsx, src/components/Popup/index.tsx, src/components/ScaleControl/index.tsx
=> chore: 给调试环境组件添加名称

src/components/LarkMap/index.tsx, src/components/LarkMap/types.ts
=> chore: 地图容器组件加调试名称

src/components/LarkMap/demos/default.tsx, src/components/LarkMap/index.tsx, src/components/LarkMap/types.ts
=> chore: 暴露图层管理器

src/components/Layers/BaseLayers/PolygonLayer/index.md
=> docs: 更新面图层 API 文档

src/components/LayerAttribute/components/ColorPicker/AntdColorPicker/index.less, src/components/LayerAttribute/components/Slider/AntdSlider.less, src/components/LayerAttribute/components/SliderRange/AntdSliderRange.less
=> fix: 修复属性组件样式问题

src/components/LayerAttribute/components/ColorPicker/AntdColorPicker/index.less
=>  fix: 修复自定义颜色组件背景色

src/components/LayerAttribute/BubbleLayerStyle/demos/default.tsx, src/components/LayerAttribute/BubbleLayerStyle/schema.ts, src/components/LayerAttribute/BubbleLayerStyle/types.ts, src/components/LayerAttribute/ChoroplethLayerStyle/demos/default.tsx, src/components/LayerAttribute/ChoroplethLayerStyle/schema.ts, src/components/LayerAttribute/ChoroplethLayerStyle/types.ts, src/components/LayerAttribute/HeatmapLayerStyle/demos/default.tsx, src/components/LayerAttribute/HeatmapLayerStyle/schema.ts, src/components/LayerAttribute/HeatmapLayerStyle/types.ts, src/components/LayerAttribute/common-schema/fill-color-collapse.ts, src/components/LayerAttribute/common-schema/lable-collapse.ts, src/components/LayerAttribute/common-schema/point-radius-collapse.ts, src/components/LayerAttribute/common-schema/stroke-collapse.ts, src/components/LayerAttribute/components/Collapse/index.tsx, src/components/LayerAttribute/components/FieldSelect/AntdSelect.tsx, src/components/LayerAttribute/components/FieldSelect/index.tsx, src/components/LayerAttribute/components/RibbonSelect/AntdRibbonSelect/constants.ts, src/components/LayerAttribute/components/RibbonSelect/AntdRibbonSelect/index.less, src/components/LayerAttribute/components/RibbonSelect/AntdRibbonSelect/index.tsx, src/components/LayerAttribute/components/RibbonSelect/index.tsx, src/components/LayerAttribute/components/index.ts, src/components/LayerAttribute/index.ts, src/components/LayerAttribute/types/index.ts, src/utils/layer-manager.ts
=> refactor: 图层选择器属性组件

src/components/LayerAttribute/BubbleLayerStyle/index.tsx, src/components/LayerAttribute/ChoroplethLayerStyle/index.tsx, src/components/LayerAttribute/HeatmapLayerStyle/index.tsx, src/components/LayerAttribute/HeatmapLayerStyle/schema.ts, src/components/LayerAttribute/common-schema/fill-color-collapse.ts, src/components/LayerAttribute/common-schema/lable-collapse.ts, src/components/LayerAttribute/common-schema/point-radius-collapse.ts, src/components/LayerAttribute/common-schema/stroke-collapse.ts, src/components/LayerAttribute/components/FormCollapse/index.less, src/components/LayerAttribute/components/FormCollapse/index.tsx, src/components/LayerAttribute/components/index.ts
=> refactor: 规范属性折叠组件名称

src/components/LayerAttribute/HeatmapLayerStyle/demos/default.tsx, src/components/LayerAttribute/common-schema/lable-collapse.ts, src/components/LayerAttribute/common-schema/stroke-collapse.ts, src/components/LayerAttribute/components/RibbonSelect/AntdRibbonSelect/constants.ts
=> fix: 属性组件更改输入input为滑块组件/色带颜色更改

src/components/ContextMenu/index.md, src/components/ContextMenu/index.tsx
=> fix: 右键菜单项类型问题

.umirc.ts
=> chore: 解决样式丢失问题

docs/common/layer/raster-layer/source.md, docs/common/layer/raster-layer/style.md, package.json, src/components/Layers/BaseLayers/RasterLayer/demos/default.tsx, src/components/Layers/BaseLayers/RasterLayer/demos/rasterData.tsx, src/components/Layers/BaseLayers/RasterLayer/demos/rasterImage.tsx, src/components/Layers/BaseLayers/RasterLayer/index.md, src/components/Layers/BaseLayers/RasterLayer/index.tsx, src/components/Layers/BaseLayers/RasterLayer/types.ts, src/components/Layers/index.ts
=> feat: 新增 RasterLayer

.github/workflows/release-notify.yml, package.json, src/components/LarkMap/demos/map-instance.tsx, src/components/LarkMap/index.md, src/components/Layers/index.ts, src/index.ts
=> fix: 修复类型导出问题

package.json, src/components/Control/ZoomControl/demos/default.tsx, src/components/Control/ZoomControl/index.md, src/components/Control/ZoomControl/index.tsx, src/components/Control/hooks/index.ts, src/components/Control/hooks/useControlElement.tsx
=> feat: 控件 ZoomControl 新增对 ReactNode 格式的支持

src/components/LayerAttribute/ChoroplethLayerStyle/demos/default.tsx, src/components/LayerAttribute/LineLayerStyle/demos/default.tsx, src/components/LayerAttribute/LineLayerStyle/schema.ts, src/components/LayerAttribute/common-schema/fill-color-collapse.ts
=> docs: 图层属性配置颜色划分默认值更改

src/components/LayerAttribute/BubbleLayerStyle/constant.ts, src/components/LayerAttribute/BubbleLayerStyle/demos/default.tsx, src/components/LayerAttribute/BubbleLayerStyle/helper.ts, src/components/LayerAttribute/BubbleLayerStyle/index.tsx, src/components/LayerAttribute/ChoroplethLayerStyle/constant.ts, src/components/LayerAttribute/ChoroplethLayerStyle/demos/default.tsx, src/components/LayerAttribute/ChoroplethLayerStyle/helper.ts, src/components/LayerAttribute/ChoroplethLayerStyle/index.tsx, src/components/LayerAttribute/common-schema/lable-collapse.ts, src/components/LayerAttribute/components/Offset/AntdOffset.less, src/components/LayerAttribute/components/Offset/AntdOffset.tsx, src/components/LayerAttribute/components/Offset/index.tsx, src/components/LayerAttribute/components/SliderRange/AntdSliderRange.tsx, src/components/LayerAttribute/components/index.ts, src/components/Layers/CompositeLayers/IconFontLayer/index.md, src/components/Layers/CompositeLayers/IconImageLayer/index.md
=> fix: label 标签配置优化

src/components/LayerAttribute/components/Offset/AntdOffset.less, src/components/LayerAttribute/components/Offset/AntdOffset.tsx
=> fix: css名称修改

src/components/LayerAttribute/LineLayerStyle/demos/default.tsx, src/components/LayerAttribute/LineLayerStyle/helper.ts, src/components/LayerAttribute/LineLayerStyle/schema.ts, src/components/LayerAttribute/common-schema/line-animate-collapse.ts
=> feat: 线属性面板开启渐变效果

src/components/LayerAttribute/BubbleLayerStyle/constant.ts, src/components/LayerAttribute/BubbleLayerStyle/demos/default.tsx, src/components/LayerAttribute/BubbleLayerStyle/helper.ts, src/components/LayerAttribute/BubbleLayerStyle/schema.ts, src/components/LayerAttribute/BubbleLayerStyle/types.ts, src/components/LayerAttribute/ChoroplethLayerStyle/demos/default.tsx, src/components/LayerAttribute/HeatmapLayerStyle/demos/default.tsx, src/components/LayerAttribute/LineLayerStyle/constant.ts, src/components/LayerAttribute/LineLayerStyle/demos/default.tsx, src/components/LayerAttribute/LineLayerStyle/helper.ts, src/components/LayerAttribute/LineLayerStyle/schema.ts, src/components/LayerAttribute/common-schema/line-animate-collapse.ts, src/components/LayerAttribute/common-schema/point-animate-collapse.ts
=> feat: 线图层动画属性配置面板

package.json
=> chore: 更新复合图层到最新依赖

.umirc.ts, docs/index.md
=> docs: 文档内容修改

.umirc.ts, README.en-US.md, README.md
=> docs: 更新 readme

src/components/LayerAttribute/LineLayerStyle/schema.ts, src/components/LayerAttribute/common-schema/fill-color-collapse.ts
=> fix: 属性配置面板颜色划分文案修改

docs/common/layer/text-layer/style.md
=> docs: 更新 TextLayer padding 默认值

src/components/LayerAttribute/common-schema/label-collapse.ts, src/components/LayerAttribute/components/Offset/AntdOffset.tsx
=> fix: 属性配置 label 问题修复

src/components/LarkMap/index.md, src/components/Layers/hooks/use-create-layer/index.ts, src/components/Layers/hooks/use-layer-event/constant.ts, src/types/layer.ts
=> fix: 添补图层事件

src/components/Control/ExportImageControl/index.md
=> fix: 修改文档单词错误

src/components/LayerAttribute/LineLayerStyle/constant.ts, src/components/Layers/hooks/use-layer-event/constant.ts, src/types/layer.ts
=> chore: 忽略无效的图层事件

docs/example/highSpeedRail/index.tsx, docs/example/marineConservation/index.tsx, docs/example/poiChart.md, package.json, src/components/Control/ExportImageControl/index.tsx, src/components/Control/FullscreenControl/index.tsx, src/components/Control/GeoLocateControl/index.tsx, src/components/Control/LayerSwitchControl/demos/default.tsx, src/components/Control/LayerSwitchControl/index.tsx, src/components/Control/MapThemeControl/index.tsx, src/components/Control/MouseLocationControl/index.tsx, src/components/Control/ScaleControl/index.tsx, src/components/Control/ZoomControl/index.tsx, src/components/Control/hooks/useL7ComponentUpdate.ts, src/components/LarkMap/hooks/use-layer-list/use-layer-list.md, src/components/LayerAttribute/LineLayerStyle/schema.ts, src/components/LayerAttribute/common-schema/fill-color-collapse.ts, src/components/LayerPopup/demos/default.tsx, src/components/LayerPopup/index.md, src/components/LayerPopup/index.tsx, src/components/LayerPopup/types.ts, src/components/LayerPopup/utils.ts, src/components/Popup/index.tsx
=> feat: 气泡图层 LayerPopup 对接 L7 LayerPopup 中的新增特性

src/components/LayerPopup/index.md, src/components/LayerPopup/index.tsx, src/components/LayerPopup/types.ts
=> fix: 修复 LayerPopup 适配复合图层问题

.umirc.ts, package.json, src/components/Layers/CompositeLayers/ChoroplethLayer/index.md
=> docs: label 支持 position

src/components/Control/FullscreenControl/demos/antd.tsx, src/components/Control/FullscreenControl/index.md
=> docs: 补充全屏组件 FullscreenControl 与 Antd 同时使用的说明

src/components/LarkMap/index.tsx
=> fix: 修复地图倾角更新不生效问题

src/components/Layers/hooks/use-create-layer/index.ts, src/components/Legend/LegendProportion/demos/map-default.tsx, src/components/Legend/LegendRamp/demos/default.tsx, src/components/Legend/LegendRamp/demos/map-default.tsx, src/components/Legend/LegendRamp/index.less, src/components/Legend/LegendRamp/index.tsx, src/components/Legend/LegendRamp/types.ts
=> refactor: 色带图例逻辑优化

src/components/Layers/hooks/use-create-layer/index.ts, src/components/Legend/LegendProportion/demos/map-default.tsx, src/components/Legend/LegendRamp/demos/default.tsx, src/components/Legend/LegendRamp/demos/map-default.tsx, src/components/Legend/LegendRamp/index.less, src/components/Legend/LegendRamp/index.tsx, src/components/Legend/LegendRamp/types.ts
=> fix: 修改图例映射区间问题

package.json, src/version.ts
=> chore: v1.3.0

src/components/LarkMap/hooks/use-scene-event/constant.ts, src/components/LarkMap/hooks/use-scene-event/index.ts
=> fix: 修复 Scene 事件绑定问题

src/components/ContextMenu/index.less, src/components/LocationSearch/types.ts
=> fix: 修复 ContextMenu 去 antd 样式依赖问题

docs/region/data/BaseDataSource.ts, docs/region/data/datavSource.ts, docs/region/data/index.ts, docs/region/data/l7Source.ts, docs/region/index.tsx, docs/region/util.ts
=> refactor: 优化展示页代码

src/components/Legend/LegendProportion/index.less
=> fix: 修复图例样式

src/components/LarkMap/demos/map-instance.tsx, src/components/LarkMap/helper.ts, src/components/LarkMap/index.md, src/components/LarkMap/index.tsx, src/components/LarkMap/types.ts
=> fix: 支持异步实例化地图

docs/common/layer/point-layer/shape.md
=> docs: 订正注册图标使用方式

src/components/Control/ExportImageControl/index.tsx, src/components/Control/FullscreenControl/index.tsx, src/components/Control/GeoLocateControl/index.tsx, src/components/Control/LayerSwitchControl/index.tsx, src/components/Control/LogoControl/index.tsx, src/components/Control/MapThemeControl/index.tsx, src/components/Control/MouseLocationControl/index.tsx, src/components/Control/ScaleControl/index.tsx, src/components/Control/ZoomControl/index.tsx, src/components/Control/hooks/useL7ComponentEvent.ts, src/components/LayerPopup/index.tsx, src/components/Popup/index.tsx
=> fix: 修复 React 18 + StrictMode 下，Control 销毁失败的问题

.umirc.ts, package.json
=> fix: 修复地图token失效问题

src/components/Control/LayerSwitchControl/demos/layerSwitchItem.tsx, src/components/Control/LayerSwitchControl/index.md
=> docs: 补充 layerSwitch 文档和 demo

src/components/Marker/types.ts
=> fix: offset 修复为 offsets

src/components/ContextMenu/index.tsx
=> fix: 修复 ContextMenu.Item 类型错误

src/components/SyncScene/demos/default.tsx, src/components/SyncScene/demos/zoomGap.tsx
=> docs: 更新双屏案例

src/components/Control/LayerSwitchControl/index.tsx, src/components/Control/LayerSwitchControl/types.ts
=> feat: 新增 LayerSwitch 支持传递 layer Id

docs/guide/faq.md
=> fix: 修改钉钉群二维码

src/components/Legend/LegendIcon/demos/custom.tsx, src/components/Legend/LegendIcon/index.less, src/components/Legend/LegendIcon/index.md, src/components/Legend/LegendIcon/index.tsx, src/components/Legend/LegendIcon/types.ts
=> feat: LegendIcons自定义icons

src/components/LocationSearch/constant.ts, src/components/LocationSearch/demos/default.tsx
=> fix: 修改 LocationSearch 高德 key 值

src/components/Legend/LegendCategories/index.tsx
=> fix:  duplicate keys in LegendCategories.

.umirc.ts
=> chore: 添加百度统计

package.json
=> chore: 支持 tree shaking

src/components/Marker/types.ts
refer: https://github.com/antvis/L7/blob/902556e18c1a3520b74965c47ca0fc65dfb2acb3/packages/component/src/marker.ts#L428
=> fix: marker event type

.fatherrc.ts, .github/workflows/lint.yml, .github/workflows/preview.yml, .github/workflows/release.yml, scripts/babel-less-to-css.js, scripts/father-plugin-less.js, scripts/loader-less-to-css.js, src/components/LarkMap/helper.ts, src/components/Marker/index.tsx
=> build: esm cmj 模式打包 less2css

package.json
=> chore: sss to sideEffects
